### ISSUE TITLE
Add example for dataloaders for new dataloader repo

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/dataloader#12]
### Description
If dataloaders are separated into own repository,  provide example how to use dataloader (similar to old NVTabular examples)

**Comment by jperez999** [comment]
Does this mean a notebook example. There is an example of usage in the documentation https://github.com/NVIDIA-Merlin/dataloader/blob/main/README.md

**Comment by viswa-nvidia** [comment]
New example development with PyT and TF is pending. @radekosmulski  will work on this.

**Comment by bschifferer** [comment]
@radekosmulski We want to provide only an example for native TensorFlow and native PyTorch. We do not want to add a dependency for Merlin Models. We want to add links/reference that this can be used with Merlin Models and what are the advantages

**Comment by EvenOldridge** [comment]
done
