### ISSUE TITLE
PyTorch Loader not working

### ISSUE THREAD

**Issue by mohammad-qloo** [NVIDIA-Merlin/dataloader#160]
I tried the Pytorch loader but it is giving me the following error:

`BufferError: DLPack only supports signed/unsigned integers, float and complex dtypes.`

but if I switched Tensorflow it works. Here's the code snippet:

```
train_dataset = merlin.io.Dataset(train_path, engine="parquet")
from merlin.loader.torch import Loader
# from merlin.dataloader.tensorflow import Loader
dl = Loader(train_dataset, batch_size=4096)
```

**Comment by jperez999** [comment]
Hello @mohammad-qloo, can you give us some further information about the data you are using in the loader. From the error you posted it seems this may be a dtype issue. Where it is possible that tensorflow is auto converting but pytorch is not.

**Comment by rnyak** [comment]
closing this issue due to low activity.
