### ISSUE TITLE
NVTabular KerasSequenceLoader cost long time to load data

### ISSUE THREAD

**Issue by Agoniii** [NVIDIA-Merlin/dataloader#46]
**Describe the bug** 
Customer use NVTabular `KerasSequenceLoader` and parquet dataset to load data, but it cost a long time, almost 1.5+ hours.

**Reproduction Steps** 
 The data file and script will be upload.

**Expected behavior**

Reduce the time of data loading.

**Environment (please complete the following information):**

Container: nvcr.io/nvidia/merlin/merlin-tensorflow:latest

Thanks!

**Comment by edknv** [comment]
I will close this issue because the issue of dataloader hanging seems resolved. The team is aware that loading list columns takes significantly longer and needs improvement: #82.
