### ISSUE TITLE
Does this work with images?

### ISSUE THREAD

**Issue by fabiozappo** [NVIDIA-Merlin/dataloader#72]
Do you have any notebooks or tutorials where you show how can I define a dataloader for image classification with pytorch?

**Comment by rnyak** [comment]
@fabiozappo we'd recommend you to explore [NVIDIA DALI](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/) library for image classification. The NVIDIA Data Loading Library (DALI) is a library for data loading and pre-processing to accelerate deep learning applications. It provides a collection of highly optimized building blocks for loading and processing image, video and audio data.
